export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const ERROR_REGISTER = 'ERROR_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const USER_DATA = 'USER_DATA'
export const ERROR_USER_DATA = 'ERROR_USER_DATA'
export const LOGOUT = 'LOGOUT'
export const ADD_CLASS = 'ADD_CLASS'
export const CLASS_ERROR = 'CLASS_ERROR'
export const GET_CLASS = 'GET_CLASS'
export const GET_CLASS_ERROR = 'GET_CLASS_ERROR'
export const REMOVE_CLASS = 'REMOVE_CLASS'
export const REMOVE_CLASS_ERROR = 'REMOVE_CLASS_ERROR'

// tags for encrypt 
export const ENCRYPT_SUCCESS = 'ENCRYPT_SUCCESS'
export const ENCRYPT_ERROR = 'ENCRYPT_ERROR'
